/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intrigus_cocoja_Pointer */

#ifndef _Included_com_intrigus_cocoja_Pointer
#define _Included_com_intrigus_cocoja_Pointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intrigus_cocoja_Pointer
 * Method:    _getFromCString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intrigus_cocoja_Pointer__1getFromCString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
