/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intrigus_cocoja_ObjcClass */

#ifndef _Included_com_intrigus_cocoja_ObjcClass
#define _Included_com_intrigus_cocoja_ObjcClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _getIvarLayout
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intrigus_cocoja_ObjcClass__1getIvarLayout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intrigus_cocoja_ObjcClass__1getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _getSuperclass
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intrigus_cocoja_ObjcClass__1getSuperclass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _getWeakIvarLayout
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intrigus_cocoja_ObjcClass__1getWeakIvarLayout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _isMetaClass
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intrigus_cocoja_ObjcClass__1isMetaClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intrigus_cocoja_ObjcClass
 * Method:    _setWeakIvarLayout
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_ObjcClass__1setWeakIvarLayout
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
