/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intrigus_cocoja_sun_lwawt_macosx_CRobot */

#ifndef _Included_com_intrigus_cocoja_sun_lwawt_macosx_CRobot
#define _Included_com_intrigus_cocoja_sun_lwawt_macosx_CRobot
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intrigus_cocoja_sun_lwawt_macosx_CRobot_MOUSE_LOCATION_UNKNOWN
#define com_intrigus_cocoja_sun_lwawt_macosx_CRobot_MOUSE_LOCATION_UNKNOWN -1L
/*
 * Class:     com_intrigus_cocoja_sun_lwawt_macosx_CRobot
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_sun_lwawt_macosx_CRobot_initIds
  (JNIEnv *, jclass);

/*
 * Class:     com_intrigus_cocoja_sun_lwawt_macosx_CRobot
 * Method:    mouseWheel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_sun_lwawt_macosx_CRobot_mouseWheel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_intrigus_cocoja_sun_lwawt_macosx_CRobot
 * Method:    initRobot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_sun_lwawt_macosx_CRobot_initRobot
  (JNIEnv *, jobject);

/*
 * Class:     com_intrigus_cocoja_sun_lwawt_macosx_CRobot
 * Method:    mouseEvent
 * Signature: (IIIIZZ)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_sun_lwawt_macosx_CRobot_mouseEvent
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_intrigus_cocoja_sun_lwawt_macosx_CRobot
 * Method:    keyEvent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_sun_lwawt_macosx_CRobot_keyEvent
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
