/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intrigus_cocoja_sun_awt_CGraphicsConfig */

#ifndef _Included_com_intrigus_cocoja_sun_awt_CGraphicsConfig
#define _Included_com_intrigus_cocoja_sun_awt_CGraphicsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intrigus_cocoja_sun_awt_CGraphicsConfig
 * Method:    nativeGetBounds
 * Signature: (I)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_intrigus_cocoja_sun_awt_CGraphicsConfig_nativeGetBounds
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
