/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intrigus_cocoja_NSApplication */

#ifndef _Included_com_intrigus_cocoja_NSApplication
#define _Included_com_intrigus_cocoja_NSApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intrigus_cocoja_NSApplication
 * Method:    _doSth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_NSApplication__1doSth
  (JNIEnv *, jclass);

/*
 * Class:     com_intrigus_cocoja_NSApplication
 * Method:    _setApplicationIconImageBuffer
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_NSApplication__1setApplicationIconImageBuffer
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_intrigus_cocoja_NSApplication
 * Method:    _setBadgeLabel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intrigus_cocoja_NSApplication__1setBadgeLabel
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
